### ISSUE TITLE
Error running make 

### ISSUE THREAD

**Issue by Kishaihd** [AB9IL/SDR-Scripts#1]
I keep getting the error: "fatal error: QAudioFormat: No such file or directory"
When running "make -j4 all" for qtradio.

**Comment by Kishaihd** [comment]
Turns out I didn't have qtbase5-dev and qtmultimedia5-dev installed. Running make again worked this time. :)

**Comment by ab9il** [comment]
Okay, good to know it is working.  Just out of curiosity, is data streaming okay if you connect to any remote servers?  I'm working on a couple of buffering issues, with a sense that QtRadio could be made to handle slow networks better.
